apiVersion: v1
kind: Service
metadata:
  name: fe
spec:
  type: LoadBalancer
  selector:
    app: fe
  ports:
  - port: 3000
    targetPort: 3000

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe
  labels:
    app: fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fe
  template:
    metadata:
      labels:
        app: fe
    spec:
      containers:
      - name: fe
        image: asia-southeast2-docker.pkg.dev/$GOOGLE_PROJECT/image-search-repo/fe:latest
