apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: asia-southeast2-docker.pkg.dev/$(PROJECT_ID)/image-search-repo/fe:latest
        env:
        - name: PROJECT_ID
          valueFrom:
            configMapKeyRef:
              name: project-config
              key: project_id
        ports:
        - containerPort: 3000